@echo off
echo Initializing git...
git init
echo Adding remote...
git remote add origin https://github.com/NoorMohamedHalith/Halith_portfolio.git
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit"
echo Renaming branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done.
pause
  